services:
  - type: web
    name: sjogu-e-skills-lab
    runtime: image
    repo: https://github.com/stevrk/Eskills_lab
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: sqlite